[book]
title = "Kasane Developer Docs"
description = "Kasane EVM compatibility documentation"
language = "en"
src = "books/en"

[build]
build-dir = "build/en"
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
site-url = "/en/"
